"use client";

import Link from "next/link";
import { useState } from "react";
import { reportHistorySeed, workspaceSource } from "@/demo/data/workspace";
import { cn, formatPersen } from "@/lib/format";

export default function ReportsPage() {
  const [selectedId, setSelectedId] = useState<string>(reportHistorySeed[0].id);
  const selected = reportHistorySeed.find((report) => report.id === selectedId) ?? reportHistorySeed[0];

  return (
    <main className="mx-auto max-w-[1280px] px-4 py-6 sm:px-6 xl:px-8 xl:py-8">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10.5px] font-bold uppercase tracking-[0.12em] text-teal-700">Belajar · Laporan</p><h1 className="mt-1 text-[26px] font-bold tracking-[-0.025em] text-ink-900">Riwayat laporan</h1><p className="mt-1 max-w-2xl text-[13px] leading-5 text-ink-500">Semua laporan tersimpan di sini. Pilih satu laporan untuk membaca ringkasannya tanpa masuk kembali ke flow simulasi.</p></div><Link href="/demo/analisis/input" className="inline-flex h-10 items-center justify-center rounded-[9px] bg-teal-700 px-4 text-[12px] font-bold text-surface hover:bg-teal-600">Buat analisis baru</Link></div>

      <div className="mt-6 grid gap-5 xl:grid-cols-[1.15fr_0.85fr]">
        <section aria-labelledby="report-list" className="overflow-hidden rounded-[14px] border border-line bg-surface"><div className="border-b border-line px-5 py-4"><h2 id="report-list" className="text-[15px] font-bold text-ink-900">Laporan tersimpan</h2><p className="mt-1 text-[11px] text-ink-400">Empat laporan · urutan terbaru</p></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] border-collapse text-left"><thead className="bg-surface-2 text-[10px] uppercase tracking-[0.1em] text-ink-400"><tr><th className="px-5 py-3">Laporan</th><th className="px-4 py-3">Usaha</th><th className="px-4 py-3">Skor</th><th className="px-4 py-3">Status</th><th className="px-5 py-3 text-right">Buka</th></tr></thead><tbody>{reportHistorySeed.map((report) => <tr key={report.id} className={cn("border-t border-line-soft text-[12px]", selectedId === report.id && "bg-teal-50")}><td className="px-5 py-4"><p className="font-bold text-ink-900">{report.title}</p><p className="mt-1 font-mono text-[9.5px] text-ink-400">{report.id} · {report.createdAt}</p></td><td className="px-4 py-4"><p className="font-semibold text-ink-700">{report.business}</p><p className="mt-0.5 text-[10px] text-ink-400">{report.area}</p></td><td className="tnum px-4 py-4 font-bold text-ink-900">{report.score}<span className="text-[9.5px] font-medium text-ink-400">/100</span></td><td className="px-4 py-4"><span className={cn("rounded-full px-2 py-1 text-[9.5px] font-bold", report.status === "Parsial" ? "bg-amber-50 text-amber-600" : "bg-success-50 text-success-600")}>{report.status}</span></td><td className="px-5 py-4 text-right"><button type="button" onClick={() => setSelectedId(report.id)} className="font-bold text-teal-700">Ringkasan →</button></td></tr>)}</tbody></table></div><div className="border-t border-line px-5 py-3"><p className="text-[10px] text-ink-400">{workspaceSource.label} · {workspaceSource.observedAt} · {workspaceSource.confidence}</p></div></section>

        <aside aria-labelledby="report-summary" className="self-start rounded-[14px] border border-line bg-surface p-5 sm:p-6"><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-[10px] text-ink-400">{selected.id}</p><h2 id="report-summary" className="mt-1 text-[18px] font-bold leading-6 text-ink-900">{selected.title}</h2></div><span className={cn("shrink-0 rounded-full px-2 py-1 text-[9.5px] font-bold", selected.status === "Parsial" ? "bg-amber-50 text-amber-600" : "bg-success-50 text-success-600")}>{selected.status}</span></div><p className="mt-3 text-[12px] text-ink-400">Dari analisis {selected.analysisId} · {selected.createdAt}</p><div className="mt-5 grid grid-cols-2 gap-3"><article className="rounded-[10px] bg-surface-2 p-4"><p className="text-[9px] font-bold uppercase tracking-[0.1em] text-ink-400">Skor</p><p className="tnum mt-2 text-[25px] font-bold text-ink-900">{selected.score}<span className="text-[10px] font-medium text-ink-400">/100</span></p></article><article className="rounded-[10px] bg-surface-2 p-4"><p className="text-[9px] font-bold uppercase tracking-[0.1em] text-ink-400">Confidence</p><p className="tnum mt-2 text-[25px] font-bold text-ink-900">{formatPersen(selected.confidencePercent)}</p></article></div><div className="mt-5 border-t border-line pt-5"><p className="text-[11px] font-bold text-ink-900">Ringkasan keputusan</p><p className="mt-2 text-[13px] leading-6 text-ink-500">{selected.summary}</p></div>{selected.status === "Parsial" ? <p className="mt-4 rounded-[9px] border border-amber-600/30 bg-amber-50 px-3 py-2.5 text-[11px] leading-5 text-amber-600">Laporan ini tetap ditandai parsial; bagian yang gagal tidak disamarkan.</p> : null}<div className="mt-6">{selected.hasFullReport ? <Link href={`/demo/laporan/${selected.id}`} className="inline-flex h-9 items-center rounded-[8px] bg-teal-700 px-3.5 text-[11.5px] font-bold text-surface">Buka laporan lengkap</Link> : <span className="inline-flex rounded-[8px] border border-line bg-surface-2 px-3.5 py-2 text-[11px] font-semibold text-ink-400">Ringkasan lengkap tersedia pada data seed berikutnya</span>}</div><p className="mt-5 text-[10px] leading-4 text-ink-400">Hasil SimuMarket AI adalah alat bantu keputusan, bukan jaminan keberhasilan usaha.</p></aside>
      </div>
    </main>
  );
}
